management/urls.py
from django.urls import path
from . import views

app_name = 'management'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import login, logout


urlpatterns = [
    path('accounts/login/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('accounts/logout/', logout, {'next_page': '/accounts/login/'}, name='logout'),

    path('admin/', admin.site.urls),
    path('', include('management.urls')),
]

management/models.py
from django.db import models
from django.utils import timezone


class Charge(models.Model):
    name = models.CharField('サイトの名前', max_length=20)
    num = models.IntegerField('件数')
    charge = models.IntegerField('件数分の合計金額')
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return '{0} {1} {2} {3}'.format(self.name, self.num, self.charge, self.created_at)

management/forms.py
from django import forms
from .models import Charge


class SearchForm(forms.Form):
    charge = forms.ModelChoiceField(
        queryset = Charge.objects, label='料金', required=False)

management/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from django.views.decorators.http import require_POST
from django.shortcuts import render
from django.views import generic
from .forms import SearchForm
from .models import Charge


#@login_required
class IndexView(generic.TemplateView):


    # template_name = 'management/management_list.html'

    model = Charge
    paginate_by = 1

    def get_context_data(self):
        """テンプレートへ渡す辞書"""
        context = super().get_context_data()
        context['form'] =  SearchForm(self.request.GET) 
        return context

    def get_queryset(self):
        """テンプレートに渡すリスト"""
        form = SearchForm(self.request.GET)
        form.is_valid()

        queryset = super().get_queryset()
        return queryset

management/templates/management/accounts/login.html
{% extends 'base.html' %} {% block contents %}

<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">ログイン</h1>

    <div class="col-md-5">

        <form action="{% url 'login' %}" method="post">
            <div class="form-group">
                {% csrf_token %} {{ form.as_p }}
                <input name="next" type="hidden" value="{{ next }}" />
            </div>
            <button type="submit" class="btn-default">ログイン</button>
        </form>
    </div>
</div>

{% endblock %}

management/templates/management/base.html
<!doctype html>
<html lang="ja">

<head>
  <title>料金管理システム</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">料金管理システム</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'management:index' %}">一覧</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">社員追加</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container">
    {% block content %} {% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
    crossorigin="anonymous"></script>
</body>

</html>

management/templates/management/management_list.html
{% extends 'management/base.html' %}

{% block content %}
<form action="" method="GET">
    {{ form }}
    <button type="submit">検索</button>
</form>

<table class="table table-bordered mt-5">
    <thead>
        <tr>
            <th>ID</th>
            <th>名前</th>
            <th>日付</th>
            <th>件数</th>
            <th>件数分の合計金額</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for management in management_list %}
        <tr>
            <td>{{ management.pk }}</td>
            <td>{{ management.name }}</td>
            <td>{{ management.num }}</td>
            <td>{{ management.charge }}</td>
            <td>{{ management.created_at }}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

<!--{% include 'management/page4.html' %} -->